### ISSUE TITLE
Cannot use date_default_timezone_set() in Wordpress Core 5.3

### ISSUE THREAD

**Issue by JakeCasey** [davidfcarr/rsvpmaker#10]
https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

Using date_default_timezone_set() interferes with Wordpress core. This plugin breaks date display with plugins like The Events Calendar.

**Comment by davidfcarr** [comment]
I've isolated the code that relies on this being set in a way that should prevent interference with other plugins.

**Comment by JakeCasey** [comment]
This seems to be fixed in recent updates, or I was wrong about the problem origin! Thank you for your time!
