### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by hiphopservers** [davidfcarr/rsvpmaker#12]
After completing the most recent update the plugin is returning a critical error on all RSVPs submitted via the site.   That data enter is saved but the white screen of death is displayed to the user.

![7e1eeaf2c31f8ee1e83345059355bd0b9e735825-1](https://user-images.githubusercontent.com/15718381/137401996-2edaaafe-062e-4443-bca2-f71f72b6d476.jpg)

These errors are returned for both desktop and mobile users of the form.

<img width="1164" alt="Screen Shot 2021-10-14 at 6 08 32 PM" src="https://user-images.githubusercontent.com/15718381/137402326-c389de37-1a25-4786-b2b2-be0d3bfc28c7.png">

I am running the latest version of WordPress.

<img width="1047" alt="Screen Shot 2021-10-14 at 6 06 48 PM" src="https://user-images.githubusercontent.com/15718381/137402451-87e8a83d-cf26-413a-a30a-ace471b076e1.png">

**Comment by davidfcarr** [comment]
Fixed in release 9.0.9. Sorry for the inconvenienc
