### ISSUE TITLE
add custom gateway

### ISSUE THREAD

**Issue by karneaud** [davidfcarr/rsvpmaker#2]
Is there a way to add custom gateways?

**Comment by davidfcarr** [comment]
May add a hook for this in the future. Can't promise it will be soon.

**Comment by karneaud** [comment]
I've taken the initiative here and I'm attempting to revamp the plugin using a more OOP modular approach with plans to leave the payment parts as add-on. Though with my current project deadline I'm not sure if i'll have the time to fully complete it. But will keep you in the loop as I progress
